<!-- <!DOCTYPE html> -->
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Mackany</title>
        <style>
     

.legal{
    color:white;
    position:absolute;
    bottom:15px;
}

#hyp{
    color:inherit;
}


        </style>
    </head>
    <body>
    <div class="col">
        <center><h1>Terms of use</h1></center>
   <h2>1. Acceptance of Terms</h2>
   <p>This is a legal agreement between You and mackany.com, Inc.,  (“Mackany” or “We”).  By clicking “I agree” to this Agreement or by accessing Mackany’s software-as-a-service (SAAS) platform, websites, or mobile applications, and using Mackany’s Service (as defined below), you become a user and agree to, and are bound by, the terms and conditions of these Terms of Service and Mackany’s <a href="https://www.mackany.com/privacy">Privacy Policy</a> (collectively, the “Agreement”) for as long as you continue to use the Service.</p>
   <p>“You”, “you”, and “your” refers to any individual who creates an account on the Service, or, if the Service is being used on behalf of an entity by an individual authorized to accept this Agreement on its behalf, then “You”, “you”, and “your” refers to that entity. If you are using and/or accessing the Service on behalf of your employer, you represent and warrant that you are authorized to enter into this Agreement on behalf of your employer. By creating an Account and/or by utilizing any Mackany Service as defined by this Agreement, you agree to be bound by the terms and conditions of this Agreement. In addition, this Agreement is applicable to your use of the Service even on a trial basis.PLEASE NOTE THAT (1) THIS AGREEMENT CONTAINS A DISPUTE RESOLUTION AND ARBITRATION AGREEMENT, INCLUDING CLASS ACTION WAIVER, THAT AFFECTS YOUR RIGHTS UNDER THIS AGREEMENT AND WITH RESPECT TO CLAIMS OR DISPUTES YOU MAY HAVE WITH Mackany. YOU MAY OPT OUT OF THE BINDING INDIVIDUAL ARBITRATION AND CLASS ACTION WAIVER AS PROVIDED (SEE SECTION XXIV.  DISPUTE RESOLUTION – ARBITRATION AGREEMENT AND CLASS ACTION WAIVER) BELOW.</p>
   <p>All software associated with the Service, including any website owned and operated by Mackany, is protected by copyright laws and international copyright treaties, as well as intellectual property laws and treaties.</p>
   <p>By using the Service, you signify your irrevocable acceptance of this Agreement. If you do not agree with the terms of this Agreement, do not use the Service.</p>
   <h2>2. Service Description</h2>
   <p>The Service includes, and is limited to, access to Mackany’s SAAS platform, websites, and mobile applications, and to Mackany’s online project management and collaboration tool (“Mackany Tool”).  Your use of the Service includes use of the Mackany Tool to create, update, share, and publish information, data, text, messages or other materials (“User Content”).  The Service also contains data, information, text, videos, photographs, links, written comments, scripts, software, graphics, and interactive features provided, generated, or made accessible on or through the Service (“Site Content”).  The term “Content” refers to and includes all User Content and Site Content.  This Agreement entitles you to the use of a single Project Manager Account (“Account”).</p>
   <p>By entering into this Agreement, Mackany grants to you, subject to your strict compliance with this Agreement, a worldwide, non-exclusive, non-sublicensable and non-transferable license to use (i.e., to display locally and/or download) Content solely for the purpose of accessing and using the Service. You may not modify, reproduce, distribute, store, or use any Content for any other purpose other than use of the Service, without prior written consent from Mackany. You also may not exploit, sell, rent, license or use the Content for any commercial use that violates any third party’s right.</p>
   <p>Any improvements, enhancements, or augmentation of the current Service, including the release of new features, tools and resources, shall be subject to the Agreement, unless explicitly stated otherwise.</p>
   <p>You agree to access the Service only through the interfaces provided by Mackany to do so, and not by any other means. As the Mackany Tool is a web-based Service, in order to access the Service, you must provide all equipment necessary, and pay any service fees associated with such access, to connect online to the World Wide Web, including a computer and modem or other access device.</p>
   <p>You agree and understand that the Service may include communications from Mackany, such as, but not limited to, notifications, service messages, release announcements, as well as support and administrative messages, and that these communications are part of the Service and you will not be able to opt out of receiving them.</p>
   <p>Mackany will provide the Service in accordance with this Agreement. At its sole direction, Mackany may modify the features of the Service, without prior notice.  However, if the Service is substantially altered, you will receive notice and an opportunity to cancel your Account.</p>
   <h2>3. Account Access</h2>
   <p>In order to use the Service, you must have a valid Account and provide Mackany with an electronic mail address and other registration information (“Account Data”). You are responsible for all activities that occur under your Account, including maintaining the confidentiality of your Account Data. Upon any unauthorized use or breach of security with your Account Data, you agree to notify Mackany immediately of any breach or unauthorized use.</p>
   <p>In order to use the Service, you agree to provide accurate, up-to-date and complete information about yourself when you sign up, and you further agree to keep all Account Data updated throughout the life of your Account. No one under the age of 16 may use the Service (see Section IV. Children Under 16). You further represent and warrant that by using or registering an Account with the Service, you are at least 16 years of age. Mackany may deny use of the Service to any person or entity, at its sole discretion. Mackany does not assume a duty to verify your information. If you provide any information that is false, inaccurate, incomplete, or outdated, or if Mackany has reasonable grounds to suspect that your information false, inaccurate, incomplete or outdated, Mackany has the right to suspend or terminate your Account and deny all current or future use of the Service (or any portion thereof).</p>
   <p>You are solely responsible for ensuring that your use of the Service is in compliance with all laws, rules and regulations applicable to you and the right to access the Service is revoked where these Terms of Service or use of the Service is prohibited or to the extent offering, sale or provision of the Service conflicts with any applicable law, rule or regulation.</p>
   <p>Mackany is not liable for any loss or damage caused by your failure to comply with the Terms of Service.</p>
   <h2>4. Children Under 16</h2>
   <p>Mackany is not directed to children, and we expect and require that any use by children under the age of 16 will only be done with the guidance, supervision, and consent of their parents, guardians and/or authorized school officials in accordance with the law. If you are a school, school district, or teacher in the country and intend to direct a student under the age of 16 to create a Mackany Account, you must and hereby do agree to comply with the U.S. Children’s Online Privacy Protection Act (“COPPA”) and, where applicable, the U.S. Family Educational Rights and Privacy Act (“FERPA”). Under these laws, you are required to obtain parental or guardian consent before your student establishes an Account or uses the Service and to notify the student’s parent or guardian of any personally identifiable information that Mackany will collect.  You must also provide the parent or guardian with a copy of our <a href="https://www.mackany.com/privacy">Privacy Policy</a>, keep all parental consent agreements on file, and provide them to us if we request them. See the <a href="http://www.ftc.gov/privacy/coppafaqs.shtm">Federal Trade Commission’s website</a> for more information.</p>
   <p>If you are a school, school district, or teacher located outside of the country and intend to direct a student to create a Mackany Account, you must and hereby do agree to obtain consent or approval from the student’s parent or guardian in accordance with similar local laws where applicable, and you agree to comply with such laws as a condition of your and your student’s use of the Service.</p>
   <h2>5. Billing &amp; Payment Terms</h2>
   <h3>a. Free Trials</h3>
   <p>If you signed up for a free trial, you will not be charged for your use of the Service during the free trial period. You may cancel at any time during the free trial period to avoid any payments. To cancel, you may use any of the cancellation methods below (see Section VI.a. How to Cancel). A cancellation will be effective immediately, and ends your free trial period. If you choose to reactivate your account after the free trial has been cancelled, your paid subscription will begin immediately and you will be billed the Subscription Fee.</p>
   <h3>b. Automatic Renewals</h3>
   <p>In order to provide continuous service, ProjectManger automatically renews all paid subscriptions for the Service (“Paid Subscriptions”) on a monthly or annual basis (“Subscription Fee”), depending on your plan. Your subscription will automatically renew on the same terms until you cancel at any time by using any of the cancellation methods below (see Section VI.a. How to Cancel). A cancellation will be effective on the next renewal date of your subscription following your notice of cancellation, and you may continue to use the Service until that time.</p>
   <h3>c. No Refund Policy</h3>
   <p>Mackany is a Paid Subscription-based Product and as such it has a no refunds policy. Your Account is subject to this policy and to the terms set forth herein. If your Account is active and in good standing, you will be charged the Subscription Fee and you will not be eligible for refunds, including for partially used subscriptions or downgraded subscriptions during a billing period. Cancellations during your subscription term do not entitle you to refunds, in whole or in part, including but not limited to applicable fees incurred by you upon billing such as conversion rate fluctuations, international bank transaction fees and overdraft fees.</p>
   <h3>d. Billing Information</h3>
   <p>You must provide and at all times must maintain accurate, complete, and current billing information, including but not limited to your billing address, credit card number, and credit card expiration date) If you fail to disclose any such information, you agree that Mackany may continue charging you for any use of the Paid Subscription unless you have terminated your Paid Subscription as set forth herein.  If you become aware of a potential breach of security to your billing information (such as credit card loss or theft), you must notify Mackany immediately.</p>
   <h3>e. Overdue Accounts</h3>
   <p>In the event Mackany is unable to collect any fees owed on your Account, you agree that Mackany may take any actions it deems necessary to collect such fees from you, including suspension or termination of your Account. You also agree that you will be responsible for all costs and expenses incurred by Mackany, such as court costs, collection fees, and attorney fees, incurred in connection with such collection efforts.</p>
   <h3>f. Fraud Protection</h3>
   <p>Mackany reserves the right at any time, and at our sole discretion, to implement fraud-protection measures including and without limitation, temporarily charging a small amount to your credit card to test validity and confirm that you are an authorized card holder.</p>
   <h3>g. Non-Use of Account</h3>
   <p>If your Account is active and in good standing, you will be charged the Subscription Fee even if you never use the Service and you will not be eligible for refunds, including for partially used subscriptions or downgraded subscriptions during a billing period. You may cancel your Paid Subscription at any time.</p>
   <h3>h. Additional Fees</h3>
   <p>Mackany reserves the right to quote additional fees for certain Services that may be arranged by mutual written agreement or paid for via Invoice. If Mackany has entered into a separate invoicing contract with you, you agree to pay all undisputed invoices within 30 days, unless different payment due terms are agreed in such a contract, and you agree that Mackany may charge interest of 1.5% monthly (or the highest rate permitted by law) for past due invoices.</p>
   <h3>i. Price Changes</h3>
   <p>Mackany may modify its Subscription Fees from time to time. In the event the Subscription Fee for your Subscription Plan has been modified, and you are required to pay a higher fee than at the time you entered into this Agreement, you will be notified at the electronic address for you on file and have the opportunity to cancel your Account.</p>
   <h3>j. Currency</h3>
   <p>All Mackany subscriptions are billed in U.S. Dollars.</p>
   <h2>6. Cancellation, Termination, and Plan Upgrades/Downgrades</h2>
   <h3>a. Cancellations</h3>
   <p>To cancel your free trial account, simply go to the “Billing” page under the “Accounts” option on the dashboard. Once your paid subscription has begun, to cancel your account, call us at 1-800-765-2495 (USA) or email us at <a href="mailto:support@mackany.com">support@mackany.com</a>. If you cancel your account through contacting our Support team, we will endeavor to process your Account cancellation within 24 hours, however we are not responsible for Subscription Fees incurred by you as a result of late cancellation requests notices to our Support team. In such case, your subscription will terminate at the end of the subscription term for which you have paid, and you will not receive any refund for any unused days of such subscription term or for any third party billing fees you incur, such as for conversion rate fluctuations, international bank transaction fees, and overdraft fees. Once your Account is cancelled, we will endeavor to notify you by electronic mail. If you choose to log back into your Account, you will be notified within the Product that further access will resume your subscription, and you agree and accept that Subscription Fees will recommence for your Paid Subscription immediately should you proceed further.</p>
   <h3>b. Plan Upgrades/Downgrades</h3>
   <p>To downgrade or upgrade your plan, simply go to the “Billing” page under the “Accounts” option on the dashboard. You may also downgrade by telephone at 1-800-765-2495 or by emailing Mackany Support at <a href="mailto:support@mackany.com">support@mackany.com</a>.</p>
   <p>Mackany is not responsible for any User Content losses should you choose to downgrade your subscription.</p>
   <h3>c. User Content</h3>
   <p>Upon the effective date of cancellation, suspension, or termination, your account will be disabled and you will not be able to access your Account or any files or other Content (including your User Content) contained in your Account. Mackany may also delete your User Content, although backup copies of information may remain in our system for some time for account recovery purposes. If you request that Mackany delete your User Content and files contained in your Account, Mackany will make every reasonable effort to do so.</p>
   <h2>7. Intellectual Property</h2>
   <p>Mackany and/or its suppliers, as applicable, retain ownership of all intellectual property and proprietary rights in the Service and in all trade names, trademarks, and service marks associated or displayed with the Service. You will not violate, obfuscate, or remove any copyright or trademark notices or other proprietary notices on, within, or associated with the Service belonging to Mackany or its suppliers. You may not reverse engineer, reverse compile, or otherwise reduce to human readable form any software associated with the Service.</p>
   <h2>8. Export Laws</h2>
   <p>You acknowledge that the Service, and any portion thereof, may be subject to the export control laws of the country. You will not violate any applicable export law or regulations through export, re-export, divert, or transfer, or disclose any part of the Service or any related technical features, material or information, either directly or indirectly.</p>
   <h2>9. Injunctive Relief</h2>
   <p>Without prejudice to and in addition to Your or Mackany’s rights under the following Dispute Resolution—Arbitration Agreement and Class Action Waiver, You agree and You acknowledge that any use of Mackany contrary to this Agreement, or any transfer, sublicensing, copying, or disclosure of technical information or materials related to the Service, may cause irreparable injury to Mackany, its affiliates, suppliers and any other party authorized by Mackany to resell, distribute, or promote the Service (“Resellers”), and under such circumstances Mackany, its affiliates, suppliers and Resellers will be entitled to equitable relief, without posting bond or other security, including, but not limited to, preliminary and permanent injunctive relief.</p>
   <h2>10. Proper Use &amp; User Content</h2>
   <p>Mackany does not claim ownership over any User Content submitted on or through the Service. Your User Content belongs to you. However, by uploading any User Content to the Service, you agree that Mackany may store and display (only to you, or others you define, depending on how you set your User Content privacy settings in the Service where applicable) your User Content solely as necessary to operate the Service. To the extent you choose to share any of your User Content with other users of the Service, you agree to allow these users (i.e. those users you or your Admin choose to specify; see Privacy Policy) to view your User Content and, to the extent applicable, share, communicate and/or collaborate with you and your User Content.</p>
   <p>Mackany does not control the User Content posted via the Service and, as such, does not guarantee the accuracy, integrity or quality of such User Content. You understand that all User Content is the sole responsibility of the person from which such User Content originated. This means that you, and not Mackany, are entirely responsible for all User Content that you upload, post, transmit or otherwise make available via your Account.</p>
   <p>Under no circumstances will Mackany be liable in any way for any User Content, including, but not limited to, for any errors or omissions in any Content, or for any loss or damage of any kind incurred as a result of the use of any Content posted, transmitted or otherwise made available via the Service. You understand that by using the Service, you may be exposed to User Content that is objectionable, offensive or indecent. You acknowledge that Mackany does not pre-screen User Content, but that Mackany and its designees shall have the right (but not an obligation) in their sole discretion to refuse, modify or move any Content that is available via the Service. Without limiting the foregoing, Mackany and its designees shall have the right to remove any User Content that violates the Agreement or is otherwise objectionable. You agree that you must evaluate, and bear all risks associated with, the use of any Content, including any reliance on the accuracy, completeness, or usefulness of such Content. In this regard, you acknowledge that you may not reasonably rely on any Content created by Mackany or submitted to Mackany. You acknowledge and agree that Mackany may preserve User Content and may also disclose User Content if required to do so legally or in the good faith belief that such preservation or disclosure is reasonably necessary to:</p>
   <ol>
      <li>comply with legal processes;</li>
      <li>enforce the Agreement;</li>
      <li>respond to claims that any Content violates the rights of third-parties; or</li>
      <li>protect the rights, property, or personal safety of Mackany, its users and the public.</li>
   </ol>
   <p>If Mackany discloses User Content to comply with legal process or respond to claims that any User Content violates the rights of third-parties, to the extent permitted by law, regulation or legal process, Mackany agrees to provide you with notice of any such legal or governmental demand and reasonably cooperate with you in any effort to seek a protective order or otherwise to contest such required disclosure.</p>
   <p>Should User Content be found or reported to violate, but not limited to, the following terms, it will be in Mackany’s sole discretion as to what action should be taken. You agree that you will not:</p>
   <ol>
      <li>transmit, post, upload or otherwise make available any User Content that is unlawful, harmful, threatening, harassing, hateful (or racially or ethnically objectionable), abusive, defamatory, vulgar, obscene, libelous, tortuous, or invasive of another’s privacy (up to, but not excluding any personal information such as an address, email, phone number without the written consent of the owner of that information).</li>
      <li>cause harm or attempt to cause harm to minors;</li>
      <li>impersonate another person or entity, including, but not limited to, a Mackany official, Service admin, author or website contributor, or falsely state or otherwise misrepresent your affiliation with another person or entity;</li>
      <li>upload, post or otherwise transmit User Content that you do not have a right to transmit under any law or under contractual or fiduciary relationships (such as inside information, proprietary and confidential information learned or disclosed as part of employment relationships or under nondisclosure agreements);</li>
      <li>upload, post or otherwise transmit any User Content that infringes any patent, trademark, trade secret, copyright, rights of privacy or publicity, or other proprietary rights of any party;</li>
      <li>use the Service to upload, post, or transmit unsolicited commercial email or “spam”. This includes unethical marketing, advertising, or any other practice that is in any way connected with “spam”, including but not limited to (a) sending mass email to recipients who haven’t requested email from you or with a fake return address, (b) promoting a site with inappropriate links, titles, descriptions, or (c) promoting your site by posting multiple submissions in public forums that are identical;</li>
      <li>use the Service to upload, post or otherwise transmit software viruses or any computer code, files or programs designed to disrupt, delete or limit the functionality of any computer software or hardware or telecommunications equipment;</li>
      <li>attempt to disrupt with or “hack” the Service or servers or networks connected to the Service, or disregard requirements, policies, rules or regulations of any networks connected to the Service;</li>
      <li>violate any applicable local, state, national or international law, either intentionally or unintentionally, including, but not limited to, regulations put into effect by the U.S. Securities and Exchange Commission, or any rules of any national or other securities exchange, including without limitation, the New York Stock Exchange, the American Stock Exchange or the NASDAQ, and any regulations having the force of law;</li>
      <li>violate acceptable use or exceed the scope of the Service that you have signed up for; for example, accessing and using the tools that you do not have a right to use, or sharing User logins, or manipulating other user’s comments or timesheets, or otherwise altering other’s User Content as an Account holder. If any user is reported to be in violation with the letter or spirit of these terms, Mackany retains the right to terminate such account at any time without further warning.</li>
      <li>take actions that impose an unreasonable or disproportionately large load on our infrastructure; or</li>
      <li>modify, copy, reproduce, alter, or publicly display any information displayed on the Service (except for your User Content), or create derivative works from our website (other than from your User Content), to the extent that such action(s) would constitute copyright infringement or otherwise violate the intellectual property rights of Mackany or any other third party, except with the prior written consent of Mackany or the appropriate third party.</li>
   </ol>
   <p>You further understand that the technical processing and transmission of the Service, including your User Content, may involve (a) transmissions over various networks; and (b) modifications to conform and adapt to technical capabilities and requirements of connecting networks or devices.</p>
   <h2>11. Use &amp; Storage Practices</h2>
   <p>You agree that Mackany is not responsible or liable for the deletion of, or the failure to store or to transmit, any User Content and other communications maintained by the Service.</p>
   <p>You further acknowledge that we reserve the right to log off users who are inactive for an extended period of time and that we reserve the right to log off users for system updates at our sole discretion. We will endeavor to notify customers in the Service prior to any downtime events.</p>
   <p>You acknowledge that Mackany may establish general practices and limits regarding Use and Storage within the Service and retains the right to create limits on use and storage at our sole discretion at any time with or without notice.</p>
   <h2>12. Beta Features</h2>
   <p>Mackany may, at its sole discretion from time to time, add new features to the Service that may be described as “Beta” features or services (collectively, “Beta Features”). These Beta Features will be considered part of the Service and all provisions of these Terms relating to the Service will apply to these Beta Features as well.</p>
   <p>Beta Features may include partially functional or non-functional features of the Service, and use of Beta Features also authorizes Mackany access to your usage data for product development research and analysis.</p>
   <p>You acknowledge that access to Beta Features is optional, and if you elect to use a Beta Feature, you agree to do so at your own risk.</p>
   <h2>13. Content on the Service</h2>
   <p>Mackany takes no responsibility for any third-party Content or User Content (including, without limitation, any viruses or other disabling features), nor does Mackany have any obligation to monitor such third-party Content. Mackany reserves the right at all times to remove or refuse to distribute any Content on the Service, such as Content which violates these Terms of Service. Mackany also reserves the right to access, read, preserve, and disclose any information as it reasonably believes is necessary to (a) satisfy any applicable laws, regulations, legal processes or governmental requests, (b) enforce these Terms of Service, including investigating potential violations, (c) detect, prevent, or mitigate fraud, security or technical concerns, (d) respond to your support requests, or (e) protect the rights, property or safety of Mackany, its users and the public.</p>
   <p>Mackany is not responsible or liable for the exercise or non-exercise of its rights under this Agreement.</p>
   <p>If Mackany discloses any such information to satisfy applicable laws, regulations, legal processes or governmental requests or to respond to your support requests, to the extent permitted by such laws, regulations or legal processes, Mackany agrees to provide you with reasonable notice of any such demand and cooperate if you seek a protective order or otherwise contest such required disclosure.</p>
   <h2>14. International Use</h2>
   <p>You acknowledge the global nature of the Internet, and as such, you agree to comply with all local regulations regarding online conduct and acceptable User Content. You further agree to comply with all applicable laws regarding the technical data transmissions exported from the country or from the country in which you reside.</p>
   <h2>15. No Resale</h2>
   <p>You agree not to sell, resell, copy, reproduce, duplicate, or otherwise exploit any portion of the Service, use of the Service, or access to the Service without express written permission of Mackany.</p>
   <h2>16. Your Representations and Warranties</h2>
   <p>You represent and warrant that (a) all of the information provided by you to Mackany to access and use the Service is correct and current; and (b) you have the authority, power, and right to enter into this Agreement and to acknowledge and agree to perform actions required of you herewith.</p>
   <h2>17. No Warranties or Representations by mackany.com, Inc.</h2>
   <p>YOU UNDERSTAND AND AGREE THAT THE SERVICE IS PROVIDED “AS IS” AND THAT, TO THE MAXIMUM EXTENT PERMITTED BY LAW, Mackany AND ITS AFFILIATES, SUPPLIERS, AND RESELLERS EXPRESSLY DISCLAIM AND EXCLUDE ALL WARRANTIES OF ANY KIND, WHETHER STATUTORY, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, SATISFACTORY QUALITY, QUIET ENJOYMENT OR TITLE. Mackany AND ITS AFFILIATES, SUPPLIERS AND RESELLERS MAKE NO WARRANTY OR REPRESENTATION REGARDING THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE SERVICE, THE SECURITY OF THE SERVICE, OR THAT THE SERVICE WILL MEET ANY USER’S REQUIREMENTS.  THIS DISCLAIMER OF WARRANTY MAY NOT BE VALID IN SOME JURISDICTIONS. YOU MAY HAVE ADDITIONAL WARRANTY RIGHTS UNDER LAW WHICH CANNOT BE WAIVED OR DISCLAIMED. Mackany DOES NOT SEEK TO LIMIT YOUR WARRANTY RIGHTS TO ANY EXTENT NOT PERMITTED BY LAW.</p>
   <p>Use of the Service is solely at your own risk. You will be solely responsible for any damages that might result related to your use of the Service. The entire risk arising out of use, security, or performance of the Service remains with you. No oral or written information or advice given by Mackany or its authorized representatives shall create a warranty or in any way increase the scope of Mackany’s obligations.</p>
   <h2>18. Indemnity</h2>
   <p>You agree to indemnify, defend, and hold harmless Mackany, its affiliates, officers, directors, employees, consultants, agents, suppliers, and Resellers from any and all third party claims, liability, damages and/or costs (including, but not limited to, attorneys’ fees as and when incurred) arising from your use of the Service, your use of your Account, your violation of these Terms of Service, or the infringement or violation by you or any other User of your Account, of any intellectual property relating to the Service (including without limitation your User Content) or other right of any person or entity.</p>
   <h2>19. Modifications to Service</h2>
   <p>Mackany reserves the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Service (or any part thereof) with or without notice at any time. If the Service is materially altered, you will receive notice and an opportunity to cancel your Account.</p>
   <h2>20. No Agency</h2>
   <p>No agency, partnership, joint venture, employee-employer, or franchiser-franchisee relationship between you and the Mackany Service is intended or created by this Agreement.</p>
   <h2>21. Limitation of Liability</h2>
   <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL Mackany OR ITS AFFILIATES, SUPPLIERS OR RESELLERS BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT, EXEMPLARY OR CONSEQUENTIAL DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR ANY OTHER PECUNIARY LOSS OR DAMAGE) ARISING OUT OF THE USE OF OR INABILITY TO USE THE SERVICE, OR THE PROVISION OF OR FAILURE TO PROVIDE TECHNICAL OR OTHER SUPPORT SERVICE, WHETHER ARISING IN TORT (INCLUDING NEGLIGENCE) CONTRACT OR ANY OTHER LEGAL THEORY, EVEN IF Mackany, ITS AFFILIATES, SUPPLIERS OR RESELLERS HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES AND NOTWITHSTANDING ANY FAILURE OF THE ESSENTIAL PURPOSE OF THIS AGREEMENT OR ANY LIMITED REMEDY HEREUNDER. IN ANY CASE AND TO THE MAXIMUM EXTENT PERMITTED BY LAW, Mackany’S, ITS AFFILIATES’, SUPPLIERS’ AND RESELLERS’ MAXIMUM CUMULATIVE LIABILITY AND YOUR EXCLUSIVE REMEDY FOR ANY CLAIMS ARISING OUT OF OR RELATED TO THIS AGREEMENT WILL BE LIMITED TO THE AMOUNT ACTUALLY PAID BY YOU FOR THE SERVICE (IF ANY) IN THE PREVIOUS TWELVE (12) MONTHS.</p>
   <p>THE FOREGOING LIMITATIONS AND EXCLUSIONS APPLY TO THE EXTENT PERMITTED BY APPLICABLE LAW IN YOUR JURISDICTION. THIS LIMITATION OF LIABILITY MAY NOT BE VALID IN SOME JURISDICTIONS. YOU MAY HAVE RIGHTS THAT CANNOT BE WAIVED UNDER CONSUMER PROTECTION AND OTHER LAWS. Mackany DOES NOT SEEK TO LIMIT ITS WARRANTY OR REMEDIES TO ANY EXTENT NOT PERMITTED BY LAW.</p>
   <h2>22. Waiver and Severability</h2>
   <p>Failure by either party to exercise any of its rights under, or to enforce any provision of, this Agreement will not be deemed a waiver or forfeiture of such rights or ability to enforce such provision. If any provision of this Agreement is held by a court of competent jurisdiction to be illegal, invalid or unenforceable, that provision will be amended to achieve as nearly as possible the same economic effect of the original provision and the remainder of this Agreement will remain in full force and effect, except that, if the Class Action Waiver clause below is found to be illegal or unenforceable, then the entire Dispute Resolution—Arbitration Agreement And Class Action Waiver section will be unenforceable, and any Dispute as defined therein will be decided by a court.</p>
   <h2>23. Governance</h2>
   <p>This Agreement shall be governed by and construed under the laws of the State of Texas, USA, as applied to agreements entered into and to be performed in Texas by Texas residents. The parties consent to the exclusive jurisdiction and venue of the federal and state courts located in and serving the County of Travis, in the City of Austin, in the State of Texas USA, except that a motion or petition to compel enforcement of the <strong>Dispute Resolution—Arbitration Agreement and Class Action Waiver</strong> clause may be brought in any court or jurisdiction where You have brought a lawsuit against Mackany, even if that lawsuit improperly were brought in a jurisdiction that was not a federal or state court serving the County of Travis, in the City of Austin, in the State of Texas USA.</p>
   <h2>24. Dispute Resolution – Arbitration Agreement and Class Action Waiver</h2>
   <p>You may opt-out of this Arbitration Agreement and Class Action Waiver (“Arbitration Agreement”) by emailing us at <a href="mailto:support@mackany.com">support@mackany.com</a> the following information: (1) your name; (2) your address; and (3) a clear statement that you do not wish to resolve disputes with us through arbitration. Your decision to opt-out of this arbitration provision will have no adverse effect on your relationship with us, but we must receive this opt-out request within 30 days from the date that you first consent to these Terms of Service. <strong>Any opt-out request received after this deadline will not be valid and you must pursue your dispute in arbitration or small claims court.</strong></p>
   <p><strong>UNLESS YOU OPT-OUT OF THESE ARBITRATION PROCEDURES AS SET FORTH ABOVE AND EXCEPT AS OTHERWISE DESCRIBED HEREIN:</strong></p>
   <p><strong>YOU AND Mackany EACH AGREE THAT, EXCEPT AS PROVIDED BELOW, ANY AND ALL DISPUTES, AS DEFINED BELOW, WHETHER PRESENTLY IN EXISTENCE OR BASED ON ACTS OR OMISSIONS IN THE PAST OR IN THE FUTURE, WILL BE RESOLVED EXCLUSIVELY AND FINALLY BY BINDING ARBITRATION, RATHER THAN IN COURT, IN ACCORDANCE WITH THIS ARBITRATION AGREEMENT.</strong></p>
   <h3>a. Arbitration</h3>
   <p>You and Mackany agree to arbitrate – rather than litigate in court – any and all claims or Disputes that may arise between you and Mackany, as defined below.</p>
   <p>For the purpose of this Arbitration Agreement the term “Mackany” means Mackany and any of Mackany’s parent companies or organizations, subsidiaries, affiliates, and each of their managers, owners, officers, directors, employees, or agents. The term “Dispute” means any claim or dispute that may arise out of or in any way relates to your relationship with Mackany, including without limitation regarding these Terms of Service, your use of the Service, or the Mackany products or services that we, our affiliates, and/or our service providers (on our behalf) may provide to you in connection with your use of the Service and/or Mackany products or services, including, without limitation, any Dispute based in contract, statute, regulation, ordinance, tort (including, but not limited to, fraud, misrepresentation, fraudulent inducement, negligence, gross negligence or reckless behavior), or any other legal or equitable theory, and includes the validity, enforceability, or scope of this Arbitration Agreement (with the exception of the enforceability of the Class Action Waiver clause below). “Dispute” is to be given the broadest possible meaning that will be enforced. However, in no event shall this Arbitration Agreement prevent you, in your individual capacity, from filing or joining a complaint with any federal, state, or local government agency that is authorized by law to seek relief against Mackany on your behalf. The arbitration between you and Mackany will be binding, and judgment on the award rendered in the arbitration may be entered in any court having jurisdiction thereof.</p>
   <p>Arbitration is a form of private dispute resolution in which parties to a contract agree to submit their Disputes and potential Disputes to a neutral third person (called an arbitrator) for a binding decision, instead of having such Dispute(s) decided in a lawsuit, in court, by a judge or jury trial. This Arbitration Agreement provides that all Disputes between you and Mackany shall be resolved by binding arbitration. Arbitration replaces the right to go to court. In the absence of this Arbitration Agreement, you might otherwise have a right or opportunity to bring claims in a court, before a judge or jury, and/or to participate in or be represented in a case filed in court by others (including, but not limited to, class actions). Entering into this Arbitration Agreement constitutes a waiver of your right to litigate claims in court and all opportunity to be heard by a judge or jury. There is no judge or jury in arbitration, and court review of an arbitration award is very limited.</p>
   <p>The arbitrator’s authority is governed by these Terms of Service. You and Mackany agree that an arbitrator must follow and be governed by this Arbitration Agreement and may only award such relief as a court of competent jurisdiction could award, limited to the same extent as a court would limit relief pursuant to these Terms of Service. An arbitrator may award attorneys’ fees and costs if a court would be authorized to do so and may issue injunctive or declaratory relief if that relief is required or authorized by the applicable law, but that injunctive or declaratory relief may not extend beyond you and your dealings with us, and may not include class or collective action relief. Discovery may be limited in arbitration, and procedures are more streamlined than in court.</p>
   <p>Notwithstanding this Arbitration Agreement, you and Mackany may bring appropriate claims against each other regarding Disputes in small claims court, if the claims fall within the small claims court’s jurisdiction, or, on an individual and not class or collective action basis, before any other federal, state, or local government agency authorized by law to hear your claims.</p>
   <p>Any dispute relating in any way to your visit to www.mackany.com or to products or Service you purchase through www.mackany.com shall be submitted to confidential arbitration in Austin, Texas, or in the federal judicial district in which you reside, except that, to the extent you have in any manner violated or threatened to violate Mackany’s intellectual property rights, Mackany may seek injunctive or other appropriate relief in any state or federal court in Austin, Texas, and you consent to exclusive jurisdiction and venue in such courts. Arbitration under this agreement shall be conducted under the rules then prevailing of the American Arbitration Association. The arbitrator’s award shall be binding and may be entered as a judgment in any court of competent jurisdiction. To the fullest extent permitted by applicable law, no arbitration under this Agreement shall be joined to an arbitration involving any other party subject to this Agreement, whether through class arbitration, collective action, consolidated proceedings, or otherwise.</p>
   <h3>b. Class Action Waiver</h3>
   <p>You and Mackany agree that all Disputes between you and Mackany will be arbitrated individually, and that there will be no class, representative, or consolidated actions in arbitration. If you or we bring a claim or Dispute in small claims court, the class action waiver will apply, and neither of the parties can bring a claim on a class or representative basis. Furthermore, neither you nor Mackany may participate in a class or representative action as a class member if the class action asserts claims or Disputes that would fall within the scope of this Arbitration Agreement if they were directly asserted by you or us. Notwithstanding the foregoing, this Arbitration Agreement shall not prohibit you or Mackany from participating solely in your individual capacity in any judgment or settlement in any litigation brought by a federal, state, or local government on behalf of you or us, excluding litigation brought by any relator or party in its capacity as a private attorney general. We both agree that this Class Action Waiver is an essential part of our Arbitration Agreement and that, if this Class Action Waiver is found to be unenforceable by any court or arbitrator, then the entire Arbitration Agreement set forth in this section will not apply to any claim or Dispute between you and us. This Class Action Waiver may not be severed from our Arbitration Agreement.</p>
   <h3>c. Informal Dispute Resolution</h3>
   <p>You and Mackany agree to try to resolve Disputes informally before resorting to arbitration. If the Dispute cannot be resolved by telephone, you agree to notify us of the Dispute by sending a written description of your claim to mackany.com, Inc – 3721 Executive Center Dr., Suite 200, Austin, TX 78731 so that we can attempt to resolve it with you. If we do not satisfactorily resolve your Dispute within 30 calendar days of receiving notice of it, then you may pursue the Dispute in arbitration. Neither you nor we may initiate arbitration without first providing the other notice of the Dispute and following the informal Dispute resolution procedure provided in this paragraph.</p>
   <h3>d. Arbitration Procedures</h3>
   <p>If the Dispute is not resolved by the Informal Dispute Resolution procedure described above, then either you or Mackany may initiate arbitration proceedings. You and Mackany agree that this website and the sale of Mackany Service or products each affects interstate commerce and that the Federal Arbitration Act applies. All arbitrations shall be conducted by the American Arbitration Association (“AAA”), and the arbitration will be conducted before a single arbitrator. The arbitration shall be commenced as an individual arbitration, and shall in no event be commenced as a representative or class arbitration. All issues shall be for the arbitrator to decide, including the scope of this Arbitration Agreement.</p>
   <p>The AAA’s rules are available on its website at www.adr.org or by calling 1-800-778-7879. If the Dispute asserted in arbitration is for less than $75,000, the AAA’s Supplementary Procedures for Consumer-Related Disputes will apply. If the Dispute asserted is for $75,000 or more, the AAA’s Commercial Arbitration Rules will apply. If there is a conflict between the AAA’s rules and this Arbitration Agreement, this Arbitration Agreement shall control. To initiate arbitration, you must send a letter requesting arbitration and describing your Dispute and any claims for relief to mackany.com, Inc – 3721 Executive Center Dr., Suite 200, Austin, TX 78731. You must also comply with the AAA’s rules regarding initiation of arbitration. We will pay all filing fees and costs for commencement of an arbitration, but you will be responsible for your own attorneys’ fees and costs unless otherwise determined by the arbitrator pursuant to the terms of this Arbitration Agreement or applicable law. We will not seek to recover our fees and costs from you in the arbitration unless your claim has been determined to be frivolous. If you are successful in the arbitration, we will pay your reasonable attorney’s fees and costs. If you obtain an award from the arbitrator greater than our last written settlement offer, we will pay you $5,000 in addition to what you have been awarded in the arbitration. The arbitration will be held in a mutually convenient location, which may include Austin, Texas or the federal judicial district within which you reside. If you seek less than $10,000, then you may choose to hold the arbitration in person, via phone, or to have it decided based on written submissions.</p>
   <h3>e. Arbitration Award</h3>
   <p>The arbitrator may award on an individual basis any relief that would be available pursuant to applicable law, except as limited by other provisions of these Terms, and will not have the power to award relief to, against, or for the benefit of any person who is not a party to the proceeding. The arbitrator shall make any award in writing but need not provide a statement of reasons unless requested by a party. Such award by the arbitrator will be final and binding on the parties, except for any right of appeal provided by the FAA or applicable state law, and may be entered in any court having jurisdiction over the parties for purposes of enforcement.</p>
   <h3>f. Severability</h3>
   <p>If any clause within this Arbitration Agreement (other than the Class Action Waiver clause above) is found to be illegal or unenforceable, that clause will be severed from this Arbitration Agreement, and the remainder of this Arbitration Agreement will be given full force and effect. If the Class Action Waiver clause is found to be illegal or unenforceable, then this entire Arbitration Agreement will be unenforceable, and the Dispute will be decided by a court.</p>
   <h2>25. General Agreement Provisions</h2>
   <p>This Agreement contains the entire understanding and agreement between the parties respecting the subject matter of this Agreement and supersedes any and all prior or contemporaneous understandings and agreements between the parties respecting such subject matter.</p>
   <p>Mackany may change the terms in its form of this Agreement for the Service at any time by posting modified or amended terms on its website. However, the Terms of Service in effect at the time you entered into this Agreement with Mackany shall govern and control, unless and until you and Mackany subsequently enter into an amendment to, or a new version of, this Agreement.</p>
   <p>This Agreement has been prepared in the English Language and such version shall be controlling in all respects and any non-English version of this Agreement is solely for accommodation purposes. Any and all rights and remedies of Mackany upon your breach or other default under this Agreement will be deemed cumulative and not exclusive of any other right or remedy conferred by this Agreement or by law or equity on Mackany, and the exercise of any one remedy will not preclude the exercise of any other.</p>
   <p>Any captions or headings appearing in this Agreement are for reference only and will not be considered in construing this Agreement.</p>
   <p>Notices to you may be made via either email or regular mail. The Service may also provide notices of changes to the Agreement or other matters by displaying notices or links to notices to you generally on the Service. Except in the case of cancellations and plan upgrades or downgrades (see Section VI.a and VI.b.), all notices or other correspondence to Mackany under this Agreement must be sent to the following electronic mail address for such purpose: <a href="mailto:support@mackany.com">support@mackany.com</a></p>
   <p>Or the following physical address:<br>Mackany, Inc.<br></p>
   <p><em>Updated July 1, 2019</em></p>
</div>
    
    </body>

    <!-- <script src="js/app.js"></script> -->
</html>
